language: python

before_install:
  - "wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh"
  - "chmod +x miniconda.sh"
  - "./miniconda.sh -b"
  - "export PATH=/home/travis/miniconda2/bin:$PATH"
  - "conda update --yes conda"
  - "conda info --all"

install:
  - "conda create --yes --name test-env python=$TRAVIS_PYTHON_VERSION numpy cython coverage"
  - "source activate test-env"
  - "pip install -r requirements.txt"
    #- "pip install coveralls"
  - "pip install . --no-deps"
  - "rm -rf coordstring/"   # clean-up to workaround coverage.py scanning coordstring/ dir
                            # while coordstring module is installed by pip elsewhere

script: coverage run --source=coordstring tests/tests.py && coverage report
#after_success: coveralls
sudo: false   # container-based testing

